In [13]:
# WENO weights on a uniform grid.
# Equation (2.21) from Shu (1998) lecture notes.

Up(r, k, l, m) = prod([r - q + 1 for q in 0:k if q ∉ [m, l]])
Us(r, k, m) = sum([Up(r, k, l, m) for l in 0:k if l != m])
D(k, m) = prod([m - l for l in 0:k if l != m])

c(k, r, j) = sum([Us(r, k, m)//D(k, m) for m in j+1:k])
cs(k, r) = [c(k , r, j) for j in 0:k-1]

cs (generic function with 1 method)

In [20]:
# Recreating entries from Table 2.1 of Shu (1998) lecture notes.

k = 3
for r in 0:k-1
    println("k = $k, r = $r: $(cs(k ,r))")
end

k = 3, r = 0: Rational{Int64}[1//3, 5//6, -1//6]
k = 3, r = 1: Rational{Int64}[-1//6, 5//6, 1//3]
k = 3, r = 2: Rational{Int64}[1//3, -7//6, 11//6]


In [19]:
# Equation (2.14) of Shu (2009).
cs(5, 2)

5-element Array{Rational{Int64},1}:
   1//30
 -13//60
  47//60
   9//20
  -1//20

In [25]:
C = zeros(Rational, 5, 3)
b = cs(5, 2)

C[1:3, 1] .= cs(3, 2)
C[2:4, 2] .= cs(3, 1)
C[3:5, 3] .= cs(3, 0)

# These should be the optimal weights and match equation (2.15) from Shu (2009).
Γ = rationalize.(C \ b; tol=√eps(Float64))

3-element Array{Rational{Int64},1}:
 1//10
 3//5 
 3//10

In [37]:
k = 5

C = zeros(Rational, 2k-1, k)
b = cs(2k-1, k-1)

for i in 1:5
    C[i:k-1+i, i] .= cs(k, k-i)
end

Γ = rationalize.(C \ b; tol=√eps(Float64))

5-element Array{Rational{Int64},1}:
  1//126
 10//63 
 10//21 
 20//63 
  5//126