In [3]:
Nx, Ny = 8, 8
xC = reshape(1:Nx, Nx, 1)
yC = reshape(1:Ny, 1, Ny)
r = @. sqrt((xC - Nx/2)^2 + (yC - Ny/2)^2)

8×8 Array{Float64,2}:
 4.24264  3.60555  3.16228  3.0  3.16228  3.60555  4.24264  5.0    
 3.60555  2.82843  2.23607  2.0  2.23607  2.82843  3.60555  4.47214
 3.16228  2.23607  1.41421  1.0  1.41421  2.23607  3.16228  4.12311
 3.0      2.0      1.0      0.0  1.0      2.0      3.0      4.0    
 3.16228  2.23607  1.41421  1.0  1.41421  2.23607  3.16228  4.12311
 3.60555  2.82843  2.23607  2.0  2.23607  2.82843  3.60555  4.47214
 4.24264  3.60555  3.16228  3.0  3.16228  3.60555  4.24264  5.0    
 5.0      4.47214  4.12311  4.0  4.12311  4.47214  5.0      5.65685

In [4]:
bottom_flux = zeros(Nx, Ny)

8×8 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [6]:
r .< 1.5

8×8 BitArray{2}:
 false  false  false  false  false  false  false  false
 false  false  false  false  false  false  false  false
 false  false   true   true   true  false  false  false
 false  false   true   true   true  false  false  false
 false  false   true   true   true  false  false  false
 false  false  false  false  false  false  false  false
 false  false  false  false  false  false  false  false
 false  false  false  false  false  false  false  false

In [8]:
bottom_flux[r .< 1.5] .= π

9-element view(::Array{Float64,1}, [19, 20, 21, 27, 28, 29, 35, 36, 37]) with eltype Float64:
 3.141592653589793
 3.141592653589793
 3.141592653589793
 3.141592653589793
 3.141592653589793
 3.141592653589793
 3.141592653589793
 3.141592653589793
 3.141592653589793

In [9]:
bottom_flux

8×8 Array{Float64,2}:
 0.0  0.0  0.0      0.0      0.0      0.0  0.0  0.0
 0.0  0.0  0.0      0.0      0.0      0.0  0.0  0.0
 0.0  0.0  3.14159  3.14159  3.14159  0.0  0.0  0.0
 0.0  0.0  3.14159  3.14159  3.14159  0.0  0.0  0.0
 0.0  0.0  3.14159  3.14159  3.14159  0.0  0.0  0.0
 0.0  0.0  0.0      0.0      0.0      0.0  0.0  0.0
 0.0  0.0  0.0      0.0      0.0      0.0  0.0  0.0
 0.0  0.0  0.0      0.0      0.0      0.0  0.0  0.0