In [2]:
f = open("tmp.dat", "w")

IOStream(<file tmp.dat>)

In [3]:
A = rand(10, 10)

10×10 Array{Float64,2}:
 0.945195   0.843855   0.296446  0.700226  …  0.238521  0.0926565  0.431643 
 0.135165   0.594817   0.681302  0.299578     0.700063  0.179107   0.0338761
 0.609415   0.534255   0.485077  0.214881     0.40144   0.799407   0.546142 
 0.541659   0.0885731  0.262373  0.367942     0.906351  0.580183   0.295403 
 0.0832995  0.925121   0.390091  0.216005     0.224471  0.823787   0.927204 
 0.641673   0.0628401  0.2476    0.686506  …  0.239542  0.612653   0.174147 
 0.515517   0.325881   0.143855  0.534164     0.156933  0.533061   0.0799939
 0.124499   0.512806   0.283673  0.384332     0.931154  0.521198   0.402992 
 0.985761   0.0583133  0.501369  0.611526     0.858579  0.0492078  0.776063 
 0.283424   0.759045   0.676082  0.516425     0.863609  0.866633   0.947901 

In [4]:
write(f, A)

800

In [5]:
close(f)

In [7]:
f32 = open("tmp32.dat", "w")

IOStream(<file tmp32.dat>)

In [8]:
B = rand(Float32, 10, 10)

10×10 Array{Float32,2}:
 0.459855  0.209698   0.287785   0.745443   …  0.630905   0.673007  0.843485
 0.135581  0.572102   0.155994   0.969178      0.759453   0.185779  0.337512
 0.501782  0.767052   0.581283   0.333334      0.0494212  0.446121  0.926873
 0.734047  0.423203   0.339858   0.936015      0.391171   0.915759  0.850957
 0.598343  0.634808   0.81803    0.738413      0.598425   0.950241  0.293855
 0.618961  0.224405   0.82085    0.165759   …  0.567706   0.255935  0.953855
 0.933598  0.972953   0.570173   0.371088      0.718539   0.789992  0.322504
 0.657076  0.0613521  0.231725   0.0282576     0.372795   0.896942  0.433679
 0.1504    0.864192   0.0461168  0.732994      0.123445   0.869912  0.341946
 0.866263  0.649838   0.363299   0.55039       0.173815   0.931864  0.586393

In [9]:
write(f32, B)

400

In [11]:
close(f32)

In [60]:
io = open("tmp.dat", "r")
M = zeros(Float64, 10, 10)
read!(io, M)

10×10 Array{Float64,2}:
 0.945195   0.843855   0.296446  0.700226  …  0.238521  0.0926565  0.431643 
 0.135165   0.594817   0.681302  0.299578     0.700063  0.179107   0.0338761
 0.609415   0.534255   0.485077  0.214881     0.40144   0.799407   0.546142 
 0.541659   0.0885731  0.262373  0.367942     0.906351  0.580183   0.295403 
 0.0832995  0.925121   0.390091  0.216005     0.224471  0.823787   0.927204 
 0.641673   0.0628401  0.2476    0.686506  …  0.239542  0.612653   0.174147 
 0.515517   0.325881   0.143855  0.534164     0.156933  0.533061   0.0799939
 0.124499   0.512806   0.283673  0.384332     0.931154  0.521198   0.402992 
 0.985761   0.0583133  0.501369  0.611526     0.858579  0.0492078  0.776063 
 0.283424   0.759045   0.676082  0.516425     0.863609  0.866633   0.947901 

In [52]:
@doc readbytes!

```
readbytes!(stream::IO, b::AbstractVector{UInt8}, nb=length(b))
```

Read at most `nb` bytes from `stream` into `b`, returning the number of bytes read. The size of `b` will be increased if needed (i.e. if `nb` is greater than `length(b)` and enough bytes could be read), but it will never be decreased.

```
readbytes!(stream::IOStream, b::AbstractVector{UInt8}, nb=length(b); all::Bool=true)
```

Read at most `nb` bytes from `stream` into `b`, returning the number of bytes read. The size of `b` will be increased if needed (i.e. if `nb` is greater than `length(b)` and enough bytes could be read), but it will never be decreased.

See [`read`](@ref) for a description of the `all` option.

Copy at most `nbytes` of decrypted data from `ctx` into `buf`. If `all=true`: wait for sufficient decrypted data to be available. Less than `nbytes` may be copied if the peer sends TLS `close_notify` or closes the connection. Returns number of bytes copied into `buf` (`<= nbytes`).


In [78]:
reinterpret(Float64, Int64(2^65))

0.0