In [24]:
# Inline helper functions.
@inline incmod1(a, n) = a == n ? one(a) : a + 1
@inline decmod1(a, n) = a == 1 ? n : a - 1

# δˣc2f, δʸc2f, and δᶻc2f calculate a difference in the x, y, and
# z-directions for a field defined at the cell centers
# and projects it onto the cell faces.

# Input: Field defined at the u-faces, which has size (Nx, Ny, Nz).
# Output: Field defined at the cell centers, which has size (Nx, Ny, Nz).
function δˣc2f(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  f[i, j, k] - f[decmod1(i,Nx), j, k]
    end
    δf
end

# Input: Field defined at the v-faces, which has size (Nx, Ny, Nz).
# Output: Field defined at the cell centers, which has size (Nx, Ny, Nz).
function δʸc2f(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  f[i, j, k] - f[i, decmod1(j,Ny), k]
    end
    δf
end

# Input: Field defined at the w-faces, which has size (Nx, Ny, Nz).
# Output: Field defined at the cell centers, which has size (Nx, Ny, Nz).
function δᶻc2f(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  f[i, j, k] - f[i, j, decmod1(k,Nz)]
    end
    δf
end

δᶻc2f (generic function with 1 method)

In [32]:
# δˣf2c, δʸf2c, and δᶻf2c calculate a difference in the x, y, and
# z-directions for a field defined at the cell faces
# and projects it onto the cell centers.

# Input: Field defined at the cell centers, which has size (Nx, Ny, Nz).
# Output: Field defined at the u-faces, which has size (Nx, Ny, Nz).
function δˣf2c(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  f[incmod1(i, Nx), j, k] - f[i, j, k]
    end
    δf
end

# Input: Field defined at the cell centers, which has size (Nx, Ny, Nz).
# Output: Field defined at the v-faces, which has size (Nx, Ny, Nz).
function δʸf2c(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  f[i, incmod1(j, Ny), k] - f[i, j, k]
    end
    δf
end

# Input: Field defined at the cell centers, which has size (Nx, Ny, Nz).
# Output: Field defined at the v-faces, which has size (Nx, Ny, Nz).
function δᶻf2c(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  f[i, j, incmod1(k, Nz)] - f[i, j, k]
    end
    δf
end

δᶻf2c (generic function with 1 method)

In [48]:
# Input: Field defined at the u-faces, which has size (Nx, Ny, Nz).
# Output: Field defined at the cell centers, which has size (Nx, Ny, Nz).
function avgˣc2f(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  (f[i, j, k] + f[decmod1(i,Nx), j, k]) / 2
    end
    δf
end

# Input: Field defined at the v-faces, which has size (Nx, Ny, Nz).
# Output: Field defined at the cell centers, which has size (Nx, Ny, Nz).
function avgʸc2f(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  (f[i, j, k] + f[i, decmod1(j,Ny), k]) / 2
    end
    δf
end

# Input: Field defined at the w-faces, which has size (Nx, Ny, Nz).
# Output: Field defined at the cell centers, which has size (Nx, Ny, Nz).
function avgᶻc2f(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  (f[i, j, k] + f[i, j, decmod1(k,Nz)]) / 2
    end
    δf
end

avgᶻc2f (generic function with 1 method)

In [53]:
# Input: Field defined at the cell centers, which has size (Nx, Ny, Nz).
# Output: Field defined at the u-faces, which has size (Nx, Ny, Nz).
function avgˣf2c(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  (f[incmod1(i, Nx), j, k] + f[i, j, k]) / 2
    end
    δf
end

# Input: Field defined at the cell centers, which has size (Nx, Ny, Nz).
# Output: Field defined at the v-faces, which has size (Nx, Ny, Nz).
function avgʸf2c(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  (f[i, incmod1(j, Ny), k] + f[i, j, k]) / 2
    end
    δf
end

# Input: Field defined at the cell centers, which has size (Nx, Ny, Nz).
# Output: Field defined at the w-faces, which has size (Nx, Ny, Nz).
function avgᶻf2c(f)
    Nx, Ny, Nz = size(f)
    δf = zeros(Nx, Ny, Nz)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        δf[i, j, k] =  (f[i, j, incmod1(k, Nz)] + f[i, j, k]) / 2
    end
    δf
end

avgᶻf2c (generic function with 1 method)

In [33]:
B = reshape([x^2 for x in 0:999], (10, 10, 10))

10×10×10 Array{Int64,3}:
[:, :, 1] =
  0  100  400   900  1600  2500  3600  4900  6400  8100
  1  121  441   961  1681  2601  3721  5041  6561  8281
  4  144  484  1024  1764  2704  3844  5184  6724  8464
  9  169  529  1089  1849  2809  3969  5329  6889  8649
 16  196  576  1156  1936  2916  4096  5476  7056  8836
 25  225  625  1225  2025  3025  4225  5625  7225  9025
 36  256  676  1296  2116  3136  4356  5776  7396  9216
 49  289  729  1369  2209  3249  4489  5929  7569  9409
 64  324  784  1444  2304  3364  4624  6084  7744  9604
 81  361  841  1521  2401  3481  4761  6241  7921  9801

[:, :, 2] =
 10000  12100  14400  16900  19600  22500  25600  28900  32400  36100
 10201  12321  14641  17161  19881  22801  25921  29241  32761  36481
 10404  12544  14884  17424  20164  23104  26244  29584  33124  36864
 10609  12769  15129  17689  20449  23409  26569  29929  33489  37249
 10816  12996  15376  17956  20736  23716  26896  30276  33856  37636
 11025  13225  15625  18225  21025  2402

In [36]:
δˣc2f(B)

10×10×10 Array{Float64,3}:
[:, :, 1] =
 -81.0  -261.0  -441.0  -621.0  -801.0  …  -1161.0  -1341.0  -1521.0  -1701.0
   1.0    21.0    41.0    61.0    81.0       121.0    141.0    161.0    181.0
   3.0    23.0    43.0    63.0    83.0       123.0    143.0    163.0    183.0
   5.0    25.0    45.0    65.0    85.0       125.0    145.0    165.0    185.0
   7.0    27.0    47.0    67.0    87.0       127.0    147.0    167.0    187.0
   9.0    29.0    49.0    69.0    89.0  …    129.0    149.0    169.0    189.0
  11.0    31.0    51.0    71.0    91.0       131.0    151.0    171.0    191.0
  13.0    33.0    53.0    73.0    93.0       133.0    153.0    173.0    193.0
  15.0    35.0    55.0    75.0    95.0       135.0    155.0    175.0    195.0
  17.0    37.0    57.0    77.0    97.0       137.0    157.0    177.0    197.0

[:, :, 2] =
 -1881.0  -2061.0  -2241.0  -2421.0  …  -2961.0  -3141.0  -3321.0  -3501.0
   201.0    221.0    241.0    261.0       321.0    341.0    361.0    381.0
   203.0    223.0 

In [41]:
δˣf2c(B)

10×10×10 Array{Float64,3}:
[:, :, 1] =
   1.0    21.0    41.0    61.0    81.0  …    121.0    141.0    161.0    181.0
   3.0    23.0    43.0    63.0    83.0       123.0    143.0    163.0    183.0
   5.0    25.0    45.0    65.0    85.0       125.0    145.0    165.0    185.0
   7.0    27.0    47.0    67.0    87.0       127.0    147.0    167.0    187.0
   9.0    29.0    49.0    69.0    89.0       129.0    149.0    169.0    189.0
  11.0    31.0    51.0    71.0    91.0  …    131.0    151.0    171.0    191.0
  13.0    33.0    53.0    73.0    93.0       133.0    153.0    173.0    193.0
  15.0    35.0    55.0    75.0    95.0       135.0    155.0    175.0    195.0
  17.0    37.0    57.0    77.0    97.0       137.0    157.0    177.0    197.0
 -81.0  -261.0  -441.0  -621.0  -801.0     -1161.0  -1341.0  -1521.0  -1701.0

[:, :, 2] =
   201.0    221.0    241.0    261.0  …    321.0    341.0    361.0    381.0
   203.0    223.0    243.0    263.0       323.0    343.0    363.0    383.0
   205.0    225.0 

In [55]:
avgˣc2f(B)

10×10×10 Array{Float64,3}:
[:, :, 1] =
 40.5  230.5  620.5  1210.5  2000.5  2990.5  4180.5  5570.5  7160.5  8950.5
  0.5  110.5  420.5   930.5  1640.5  2550.5  3660.5  4970.5  6480.5  8190.5
  2.5  132.5  462.5   992.5  1722.5  2652.5  3782.5  5112.5  6642.5  8372.5
  6.5  156.5  506.5  1056.5  1806.5  2756.5  3906.5  5256.5  6806.5  8556.5
 12.5  182.5  552.5  1122.5  1892.5  2862.5  4032.5  5402.5  6972.5  8742.5
 20.5  210.5  600.5  1190.5  1980.5  2970.5  4160.5  5550.5  7140.5  8930.5
 30.5  240.5  650.5  1260.5  2070.5  3080.5  4290.5  5700.5  7310.5  9120.5
 42.5  272.5  702.5  1332.5  2162.5  3192.5  4422.5  5852.5  7482.5  9312.5
 56.5  306.5  756.5  1406.5  2256.5  3306.5  4556.5  6006.5  7656.5  9506.5
 72.5  342.5  812.5  1482.5  2352.5  3422.5  4692.5  6162.5  7832.5  9702.5

[:, :, 2] =
 10940.5  13130.5  15520.5  18110.5  …  27080.5  30470.5  34060.5  37850.5
 10100.5  12210.5  14520.5  17030.5     25760.5  29070.5  32580.5  36290.5
 10302.5  12432.5  14762.5  17292.5   

In [54]:
avgˣf2c(B)

10×10×10 Array{Float64,3}:
[:, :, 1] =
  0.5  110.5  420.5   930.5  1640.5  2550.5  3660.5  4970.5  6480.5  8190.5
  2.5  132.5  462.5   992.5  1722.5  2652.5  3782.5  5112.5  6642.5  8372.5
  6.5  156.5  506.5  1056.5  1806.5  2756.5  3906.5  5256.5  6806.5  8556.5
 12.5  182.5  552.5  1122.5  1892.5  2862.5  4032.5  5402.5  6972.5  8742.5
 20.5  210.5  600.5  1190.5  1980.5  2970.5  4160.5  5550.5  7140.5  8930.5
 30.5  240.5  650.5  1260.5  2070.5  3080.5  4290.5  5700.5  7310.5  9120.5
 42.5  272.5  702.5  1332.5  2162.5  3192.5  4422.5  5852.5  7482.5  9312.5
 56.5  306.5  756.5  1406.5  2256.5  3306.5  4556.5  6006.5  7656.5  9506.5
 72.5  342.5  812.5  1482.5  2352.5  3422.5  4692.5  6162.5  7832.5  9702.5
 40.5  230.5  620.5  1210.5  2000.5  2990.5  4180.5  5570.5  7160.5  8950.5

[:, :, 2] =
 10100.5  12210.5  14520.5  17030.5  …  25760.5  29070.5  32580.5  36290.5
 10302.5  12432.5  14762.5  17292.5     26082.5  29412.5  32942.5  36672.5
 10506.5  12656.5  15006.5  17556.5   

In [57]:
avgʸf2c(avgˣf2c(B))

10×10×10 Array{Float64,3}:
[:, :, 1] =
  55.5  265.5   675.5  1285.5  2095.5  3105.5  4315.5  5725.5  7335.5  4095.5
  67.5  297.5   727.5  1357.5  2187.5  3217.5  4447.5  5877.5  7507.5  4187.5
  81.5  331.5   781.5  1431.5  2281.5  3331.5  4581.5  6031.5  7681.5  4281.5
  97.5  367.5   837.5  1507.5  2377.5  3447.5  4717.5  6187.5  7857.5  4377.5
 115.5  405.5   895.5  1585.5  2475.5  3565.5  4855.5  6345.5  8035.5  4475.5
 135.5  445.5   955.5  1665.5  2575.5  3685.5  4995.5  6505.5  8215.5  4575.5
 157.5  487.5  1017.5  1747.5  2677.5  3807.5  5137.5  6667.5  8397.5  4677.5
 181.5  531.5  1081.5  1831.5  2781.5  3931.5  5281.5  6831.5  8581.5  4781.5
 207.5  577.5  1147.5  1917.5  2887.5  4057.5  5427.5  6997.5  8767.5  4887.5
 135.5  425.5   915.5  1605.5  2495.5  3585.5  4875.5  6365.5  8055.5  4495.5

[:, :, 2] =
 11155.5  13365.5  15775.5  18385.5  …  27415.5  30825.5  34435.5  23195.5
 11367.5  13597.5  16027.5  18657.5     27747.5  31177.5  34807.5  23487.5
 11581.5  13831.5 

In [60]:
ũ⋅∇u(x) = x^2

ErrorException: syntax: "∇u(x)" is not a valid function argument name