In [2]:
cd("/home/gridsan/aramadhan/Oceananigans.jl/")
pwd()
using Pkg
Pkg.activate(".")

"/home/gridsan/aramadhan/Oceananigans.jl/Project.toml"

In [3]:
using CuArrays

In [44]:
using Adapt

In [45]:
Adapt.adapt_structure(to, A::SubArray{<:Any,<:Any,AT}) where {AT} = SubArray(adapt(to, parent(A)), adapt.(Ref(to), parentindices(A)))

In [10]:
N = 8
L = collect(1:8) .^ 2

8-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36
 49
 64

In [11]:
r_inds = [1, collect(N:-1:2)...]

8-element Array{Int64,1}:
 1
 8
 7
 6
 5
 4
 3
 2

In [12]:
Lr = view(L, r_inds)

8-element view(::Array{Int64,1}, [1, 8, 7, 6, 5, 4, 3, 2]) with eltype Int64:
  1
 64
 49
 36
 25
 16
  9
  4

In [13]:
Lr .* L

8-element Array{Int64,1}:
   1
 256
 441
 576
 625
 576
 441
 256

In [46]:
G = collect(1:8) .^ 2 .|> Float64 |> CuArray

8-element CuArray{Float64,1}:
  1.0
  4.0
  9.0
 16.0
 25.0
 36.0
 49.0
 64.0

In [54]:
r_inds = [1, collect(N:-1:2)...] |> CuArray
r_inds = N:-1:1

8:-1:1

In [55]:
Gr = view(G, r_inds)

8-element view(::CuArray{Float64,1}, 8:-1:1) with eltype Float64:
  4.0
  9.0
 16.0
 25.0
 36.0
 49.0
 64.0
  1.0

In [56]:
H = ones(N) |> CuArray

8-element CuArray{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [57]:
typeof(Gr)

SubArray{Float64,1,CuArray{Float64,1},Tuple{StepRange{Int64,Int64}},true}

In [58]:
Gr .* G

8-element CuArray{Float64,1}:
   4.0
 576.0
 784.0
 900.0
 900.0
 784.0
 576.0
   4.0