In [1]:
using Random, Statistics
using FFTW

In [2]:
N = 8
R = rand(MersenneTwister(0), N)
R = R .- mean(R)

8-element Array{Float64,1}:
  0.4900442230630878 
  0.5767532530121119 
 -0.16903748678063935
 -0.15627443844806   
 -0.05472317558312356
 -0.1301267268724019 
 -0.2913016189822949 
 -0.2653340294086798 

In [3]:
R2 = copy(R)
R2 .= cat(R2[1:2:N], R2[N:-2:2]; dims=1)

8-element Array{Float64,1}:
  0.4900442230630878 
 -0.16903748678063935
 -0.05472317558312356
 -0.2913016189822949 
 -0.2653340294086798 
 -0.1301267268724019 
 -0.15627443844806   
  0.5767532530121119 

In [6]:
@inline W(M, k) = exp(-2im*π*k/M)

R3 = fft(R2)

R4 = zeros(N)
for k in 0:N-1
    R4[k+1] = 2 * real(W(4N, k) * R3[k+1])
end

R4

8-element Array{Float64,1}:
  4.440892098500626e-16
  2.8423915810257907   
  1.2525286497647694   
  1.1066138351200558   
  0.038785032156569685 
 -1.0474753422685552   
 -0.7467529134050761   
 -0.5353031832400937   

In [11]:
R_FCT = FFTW.r2r(R, FFTW.REDFT10)

8-element Array{Float64,1}:
  4.440892098500626e-16
  2.842391581025791    
  1.2525286497647694   
  1.1066138351200558   
  0.038785032156569685 
 -1.0474753422685554   
 -0.7467529134050761   
 -0.5353031832400938   

In [12]:
R4 ≈ R_FCT

true