In [1]:
using Random, Statistics
using FFTW

In [44]:
N = 8
R = rand(MersenneTwister(0), N)
R = R .- mean(R)

8-element Array{Float64,1}:
  0.4900442230630878 
  0.5767532530121119 
 -0.16903748678063935
 -0.15627443844806   
 -0.05472317558312356
 -0.1301267268724019 
 -0.2913016189822949 
 -0.2653340294086798 

In [45]:
R2 = copy(R)
R2 .= cat(R2[1:2:N], R2[N:-2:2]; dims=1)

8-element Array{Float64,1}:
  0.4900442230630878 
 -0.16903748678063935
 -0.05472317558312356
 -0.2913016189822949 
 -0.2653340294086798 
 -0.1301267268724019 
 -0.15627443844806   
  0.5767532530121119 

In [46]:
@inline W(M, k) = exp(-2im*π*k/M)

R3 = fft(R2)

R4 = zeros(N)
for k in 0:N-1
    R4[k+1] = 2 * real(W(4N, k) * R3[k+1])
end

R4

8-element Array{Float64,1}:
  4.440892098500626e-16
  2.8423915810257907   
  1.2525286497647694   
  1.1066138351200558   
  0.038785032156569685 
 -1.0474753422685552   
 -0.7467529134050761   
 -0.5353031832400937   

In [47]:
ω_4N_k⁻ = W.(4N, 0:-1:-(N-1))
ω_4N_k⁻[1] *= 1/2

R5 = ω_4N_k⁻ .* R4

8-element Array{Complex{Float64},1}:
 2.220446049250313e-16 - 0.0im                 
    2.7877758238121615 + 0.5545230888382534im  
    1.1571855834016684 + 0.4793219628275934im  
    0.9201157764559056 + 0.614801706240365im   
   0.02742515924644873 + 0.027425159246448727im
   -0.5819461199864289 - 0.8709439167325115im  
   -0.2857699680304852 - 0.689909732538123im   
  -0.10443247039456843 - 0.5250174826748771im  

In [50]:
R6 = ifft(R5)

R7 = zeros(N)
R7_p = view(R7, [1:2:N..., N:-2:2...])

@. R7_p = real(R6)

8-element view(::Array{Float64,1}, [1, 3, 5, 7, 8, 6, 4, 2]) with eltype Float64:
  0.4900442230630877  
 -0.16903748678063935 
 -0.054723175583123534
 -0.2913016189822949  
 -0.2653340294086797  
 -0.1301267268724019  
 -0.15627443844806002 
  0.5767532530121119  

In [51]:
R7 .≈ R

8-element BitArray{1}:
 true
 true
 true
 true
 true
 true
 true
 true