In [335]:
function dct_permute!(A, B)
    Nz = length(A)
    for k in 1:Nz
        if isodd(k)
            B[floor(Int, k/2) + 1] = A[k]
        else
            B[Nz - floor(Int, (k-1)/2)] = A[k]
        end
    end
end

dct_permute! (generic function with 1 method)

In [342]:
function idct_permute!(A, B)
    Nz = length(A)
    for k in 1:Nz
        if k <= Nz/2
            B[2k-1] = A[k]
        else
            # B[k] = A[Nz-2(k-ceil(Int, Nz/2)-1)]
            B[2(Nz-k+1)] = A[k]
        end
    end
end

idct_permute! (generic function with 1 method)

In [343]:
B = zeros(Int, 6)
C = zeros(Int, 6)
A = collect(1:6)

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [344]:
dct_permute!(A, B)

In [345]:
B

6-element Array{Int64,1}:
 1
 3
 5
 6
 4
 2

In [346]:
idct_permute!(B, C)

In [347]:
C

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [307]:
function dct_permute!(A, B)
    Nx, Ny, Nz = size(A)
    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        if isodd(k)
            B[i, j, k] = A[i, j, floor(Int, k/2) + 1]
        else
            B[i, j, k] = A[i, j, Nz - floor(Int, (k-1)/2)]
        end
    end
end

dct_permute! (generic function with 1 method)

In [308]:
Nx, Ny, Nz = 4, 4, 4
t = reshape(collect(1:Nx*Ny*Nz), Nx, Ny, Nz)

4×4×4 Array{Int64,3}:
[:, :, 1] =
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

[:, :, 2] =
 17  21  25  29
 18  22  26  30
 19  23  27  31
 20  24  28  32

[:, :, 3] =
 33  37  41  45
 34  38  42  46
 35  39  43  47
 36  40  44  48

[:, :, 4] =
 49  53  57  61
 50  54  58  62
 51  55  59  63
 52  56  60  64

In [309]:
B = zeros(size(t))
dct_permute!(t, B)

In [310]:
B

4×4×4 Array{Float64,3}:
[:, :, 1] =
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

[:, :, 2] =
 49.0  53.0  57.0  61.0
 50.0  54.0  58.0  62.0
 51.0  55.0  59.0  63.0
 52.0  56.0  60.0  64.0

[:, :, 3] =
 17.0  21.0  25.0  29.0
 18.0  22.0  26.0  30.0
 19.0  23.0  27.0  31.0
 20.0  24.0  28.0  32.0

[:, :, 4] =
 33.0  37.0  41.0  45.0
 34.0  38.0  42.0  46.0
 35.0  39.0  43.0  47.0
 36.0  40.0  44.0  48.0